# Generated by Django 5.0.6 on 2024-07-31 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(3, 'ORDER_DELIVERED'), (2, 'ORDER_PROCESSED'), (4, 'ORDER_REJECTED')], default=0),
        ),
    ]
